steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - http_sample_function_1
  - --source=.
  - --trigger-http
  - --runtime=python37
  - --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY